title: 
email: devnull-vortex@protonmail.com
description: >-
  Com mais de 15 anos de experiência em Garantia de Qualidade de Software (QA), tenho um histórico comprovado de sucesso na entrega de soluções de software de alta qualidade. Minha expertise abrange aplicações web e móveis, com foco em tecnologias avançadas e planejamento de escopo de QA eficaz. Possuo fortes habilidades analíticas, que aplico de forma eficaz a sistemas e processos de software. Acredito nas melhores práticas de comunicação e estou sempre buscando novos conhecimentos técnicos e comportamentais. Minha adaptabilidade me permite trabalhar em diferentes metodologias, ambientes e estruturas de trabalho.
baseurl: "/"
url: "https://leonardosetti.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  leonardosetti

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md
  - resume.md

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/