# Custom configurations

title: Leonardo Setti
email: devnull-vortex@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Este espaço ainda está em desenvolvimento e testes.
baseurl: "" # não fuça aqui, sempre dá problema!
url: "" # não precisa mexer aqui também, deixa quieto por enquanto.
twitter_username: issaeFera
github_username:  leonardosetti

# Build settings
# theme: minima
remote_theme: leonardosetti/minimal-mistakes
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
